spring.application.name=Helpdesk

spring.datasource.url=jdbc:postgresql://dpg-d71rq37diees73bvo0sg-a:5432/helpdesk_db_rwnu
spring.datasource.username= helpdesk_db_rwnu_user
spring.datasource.password= CgxIYugmvw2LyM32vHAsVy7R7RxlvYtz
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
